---
deployment:
  tasks:
    - export DEPLOYPATH=/home/electroc/helpdesk.electrocreditosdelcauca.com/
    
    # Copy directories
    - /bin/cp -R config controller models public view services cargues Event vendor $DEPLOYPATH

    # Copy individual PHP files
    - /bin/cp index.php sso-login.php server.php export_desempeno.php export_flujos.php $DEPLOYPATH

    # Copy configuration files (ensure .htaccess is copied)
    - /bin/cp .htaccess $DEPLOYPATH
    
    # Optional: Uncomment if you want to deploy the environment file (be careful not to overwrite production credentials)
    # - /bin/cp .env $DEPLOYPATH